#!/bin/bash -x
export JAVA_HOME=$GRAAL_HOME/jdk1.7.0_10/fastdebug/
export JAVA_OPTS="-graal -Ddelite.home.dir=~/work/research/code/virt/Delite"

DEBUG=""
DEBUGGER="-Xdebug -Xrunjdwp:transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n"

[ -n "$METHOD_FILTER" ] &&  DEBUG="-G:Dump=Playground -G:MethodFilter=$METHOD_FILTER $DEBUGGER"

$JAVA_HOME/bin/java -graal  -XX:+BootstrapGraal $DEBUG \
-Xms512M -Xmx2G -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled \
-jar ~/bin/sbt-launch12.jar "$@"
