#!/bin/bash -x
if [ -n "$DEBUG" ]; 
then
  export JAVA_HOME=$EGRAAL_HOME/jdk1.7.0_10/debug/
else
  export JAVA_HOME=$EGRAAL_HOME/jdk1.7.0_10/product/
fi

export JAVA_OPTS="-graal"

DUMP=""
DEBUGGER=""
[ -n "$DEBUG" ] && DEBUGGER="-Xdebug -Xrunjdwp:transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n"

[ -n "$METHOD_FILTER" ] &&  DUMP="-G:Dump=LMS -G:MethodFilter=$METHOD_FILTER"

$JAVA_HOME/bin/java -graal  -XX:+BootstrapGraal $DUMP $DEBUGGER \
-Xms512M -Xmx2G -XX:MaxPermSize=512M -XX:+CMSClassUnloadingEnabled \
-jar ~/bin/sbt-launch12.jar "$@"
